export const TYPE_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  Normal:   { bg: 'bg-[#A8A77A]', text: 'text-white', border: 'border-[#A8A77A]' },
  Fire:     { bg: 'bg-[#EE8130]', text: 'text-white', border: 'border-[#EE8130]' },
  Water:    { bg: 'bg-[#6390F0]', text: 'text-white', border: 'border-[#6390F0]' },
  Electric: { bg: 'bg-[#F7D02C]', text: 'text-gray-900', border: 'border-[#F7D02C]' },
  Grass:    { bg: 'bg-[#7AC74C]', text: 'text-white', border: 'border-[#7AC74C]' },
  Ice:      { bg: 'bg-[#96D9D6]', text: 'text-gray-900', border: 'border-[#96D9D6]' },
  Fighting: { bg: 'bg-[#C22E28]', text: 'text-white', border: 'border-[#C22E28]' },
  Poison:   { bg: 'bg-[#A33EA1]', text: 'text-white', border: 'border-[#A33EA1]' },
  Ground:   { bg: 'bg-[#E2BF65]', text: 'text-gray-900', border: 'border-[#E2BF65]' },
  Flying:   { bg: 'bg-[#A98FF3]', text: 'text-white', border: 'border-[#A98FF3]' },
  Psychic:  { bg: 'bg-[#F95587]', text: 'text-white', border: 'border-[#F95587]' },
  Bug:      { bg: 'bg-[#A6B91A]', text: 'text-white', border: 'border-[#A6B91A]' },
  Rock:     { bg: 'bg-[#B6A136]', text: 'text-white', border: 'border-[#B6A136]' },
  Ghost:    { bg: 'bg-[#735797]', text: 'text-white', border: 'border-[#735797]' },
  Dragon:   { bg: 'bg-[#6F35FC]', text: 'text-white', border: 'border-[#6F35FC]' },
  Dark:     { bg: 'bg-[#705746]', text: 'text-white', border: 'border-[#705746]' },
  Steel:    { bg: 'bg-[#B7B7CE]', text: 'text-gray-900', border: 'border-[#B7B7CE]' },
  Fairy:    { bg: 'bg-[#D685AD]', text: 'text-white', border: 'border-[#D685AD]' },
};
